apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  # encode your token with base64 with command: echo -n "<your-token>" | base64, and paste the output here
  token: Z2hwX3IwcnlvWGpYeW1ObzJMcWVEb05mdGxGczJCWGlFcjJnOEtIZQ==
